currency:
  api-url: "http://www.cbr.ru/scripts/XML_daily.asp"

spring:
  cache:
    type: simple
    cache-names: currencyRates, convertCurrency
    ehcache:
      config: classpath:ehcache.xml

resilience4j.circuitbreaker:
  instances:
    convertCurrency:
      registerHealthIndicator: true
      sliding-window-size: 10
      minimum-number-of-calls: 5
      failure-rate-threshold: 50
      wait-duration-in-open-state: 60s
      permitted-number-of-calls-in-half-open-state: 3